[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
addopts = "-s -v --cache-clear --reuse-db"
python_files = ["test_*.py"]
python_functions = "test_*"
cache_dir = "/tmp"


[tool.black]
target-version = ['py312']
line-length = 120
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | archive
    | docs
  )/
)
'''


[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
skip = 'archive,docs'



[tool.mypy]
plugins = [
    "mypy_django_plugin.main",
    "mypy_drf_plugin.main",
]
python_version = "3.12"
warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true
namespace_packages = true

# [[tool.mypy.overrides]]
# ignore_missing_imports=true


[tool.django-stubs]
django_settings_module = "config.settings"