# Generated by Django 5.2.3 on 2025-07-13 17:01

import django.db.models.deletion
import food.enums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
            ],
            options={
                "db_table": "dishes",
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
            ],
            options={
                "db_table": "restaurants",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("cooking_rejected", "Cooking rejected"),
                            ("cooking", "Cooking"),
                            ("cooked", "Cooked"),
                            ("delivery_lookup", "Delivery lookup"),
                            ("delivery", "Delivery"),
                            ("delivered", "Delivered"),
                            ("not_delivered", "Not delivered"),
                            ("cancelled_by_customer", "Cancelled by customer"),
                            ("cancelled_by_manager", "Cancelled by manager"),
                            ("cancelled_by_admin", "Cancelled by admin"),
                            ("cancelled_by_restaurant", "Cancelled by restaurant"),
                            ("cancelled_by_driver", "Cancelled by driver"),
                            ("failed", "Failed"),
                        ],
                        default=food.enums.OrderStatus["NOT_STARTED"],
                        max_length=50,
                    ),
                ),
                (
                    "delivery_provider",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("eta", models.DateField()),
                ("total", models.PositiveIntegerField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.SmallIntegerField()),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="food.dish"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="food.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_items",
            },
        ),
        migrations.AddField(
            model_name="dish",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes",
                to="food.restaurant",
            ),
        ),
    ]
